# Generated by Django 2.2.12 on 2020-05-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapistApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('nickname', models.CharField(max_length=200)),
            ],
        ),
    ]
